fix concurrent rw on touchedLeaves map (#11566)
got crash on sepolia due to concurrent rw panic:

```
fatal error: concurrent map iteration and map write

goroutine 125102027 [running, locked to thread]:
github.com/erigontech/erigon/cl/phase1/core/state/raw.(*BeaconState).CopyInto(0xc04b46c908, 0xc04b46cb48)
        github.com/erigontech/erigon/cl/phase1/core/state/raw/copy.go:83 +0xd93
github.com/erigontech/erigon/cl/phase1/core/state.(*CachingBeaconState).CopyInto(0xc08b77cea0, 0xc08b77d2c0)
        github.com/erigontech/erigon/cl/phase1/core/state/copy.go:28 +0x74
github.com/erigontech/erigon/cl/phase1/core/state.(*CachingBeaconState).Copy(0xc08b77cea0)
        github.com/erigontech/erigon/cl/phase1/core/state/copy.go:66 +0x37
github.com/erigontech/erigon/cl/phase1/stages.emitNextPaylodAttributesEvent(0xc05c490c40, 0x56133a, {0x64, 0xac, 0xff, 0x77, 0xa0, 0x8e, 0xc2, 0x14, ...}, ...)
        github.com/erigontech/erigon/cl/phase1/stages/forkchoice.go:220 +0x20b
github.com/erigontech/erigon/cl/phase1/stages.postForkchoiceOperations({0x3215620, 0xc05bc64820}, {0x324d000, 0xc08a900280}, {0x322b8c8, 0xc09a1ae4c0}, 0xc05c490c40, 0x56133a, {0x64, 0xac, ...})
        github.com/erigontech/erigon/cl/phase1/stages/forkchoice.go:332 +0x3cb
github.com/erigontech/erigon/cl/phase1/stages.doForkchoiceRoutine({0x3215620, 0xc05bc64820}, {0x322b8c8, 0xc09a1ae4c0}, 0xc05c490c40, {0x40, 0x2b098, 0x2b099, 0x56133a, 0x56133a, ...})
        github.com/erigontech/erigon/cl/phase1/stages/forkchoice.go:357 +0x30e
github.com/erigontech/erigon/cl/clstages.(*StageGraph[...]).StartWithStage.func1()
        github.com/erigontech/erigon/cl/clstages/clstages.go:54 +0x6e
created by github.com/erigontech/erigon/cl/clstages.(*StageGraph[...]).StartWithStage in goroutine 3439
        github.com/erigontech/erigon/cl/clstages/clstages.go:50 +0x3a5
```