rpc: use synctest for TestClientCancelHTTP to fix CI flakiness (#20368)
Replace real TCP connections with in-memory net.Pipe-based listener for
the HTTP cancel test, wrapped in synctest.Test for deterministic
fake-time execution. The test now runs in ~0s instead of timing out on
slow CI runners.

WebSocket cancel test keeps real TCP due to complex goroutine shutdown
dependencies incompatible with synctest's bubble requirements.

err: 
```
[WARN] [04-07|01:51:47.496] Cannot register RPC callback [invalidRets1] - error must the last return value 
[WARN] [04-07|01:51:47.496] Cannot register RPC callback [invalidRets2] - error must the last return value 
[WARN] [04-07|01:51:47.497] Cannot register RPC callback [invalidRets3] - maximum 2 return values are allowed, got 3 
[WARN] [04-07|01:51:47.507] Cannot register RPC callback [invalidRets1] - error must the last return value 
[WARN] [04-07|01:51:47.507] Cannot register RPC callback [invalidRets2] - error must the last return value 
[WARN] [04-07|01:51:47.507] Cannot register RPC callback [invalidRets3] - maximum 2 return values are allowed, got 3 
[WARN] [04-07|01:51:47.510] Cannot register RPC callback [invalidRets1] - error must the last return value 
[WARN] [04-07|01:51:47.510] Cannot register RPC callback [invalidRets2] - error must the last return value 
[WARN] [04-07|01:51:47.510] Cannot register RPC callback [invalidRets3] - maximum 2 return values are allowed, got 3 
[WARN] [04-07|01:51:47.512] [rpc] served                             method=test_returnError reqid=1 err=testError errdata="testError data"
[WARN] [04-07|01:51:47.513] Cannot register RPC callback [invalidRets1] - error must the last return value 
[WARN] [04-07|01:51:47.513] Cannot register RPC callback [invalidRets2] - error must the last return value 
[WARN] [04-07|01:51:47.513] Cannot register RPC callback [invalidRets3] - maximum 2 return values are allowed, got 3 
[WARN] [04-07|01:51:47.515] [rpc] served                             method=no_such_method reqid=3 err="the method no_such_method does not exist/is not available"
[WARN] [04-07|01:51:47.516] Cannot register RPC callback [invalidRets1] - error must the last return value 
[WARN] [04-07|01:51:47.516] Cannot register RPC callback [invalidRets2] - error must the last return value 
[WARN] [04-07|01:51:47.516] Cannot register RPC callback [invalidRets3] - maximum 2 return values are allowed, got 3 
[WARN] [04-07|01:51:47.517] Cannot register RPC callback [invalidRets1] - error must the last return value 
[WARN] [04-07|01:51:47.517] Cannot register RPC callback [invalidRets2] - error must the last return value 
[WARN] [04-07|01:51:47.518] Cannot register RPC callback [invalidRets3] - maximum 2 return values are allowed, got 3 
[WARN] [04-07|01:51:47.519] [rpc] served                             method=eth_subscribe reqid=1 err="no \"foo_bar\" subscription in eth namespace"
[WARN] [04-07|01:51:47.519] [rpc] served                             method=eth_subscribe reqid=2 err="no \"foo_bar\" subscription in eth namespace"
[WARN] [04-07|01:51:47.520] Cannot register RPC callback [invalidRets1] - error must the last return value 
[WARN] [04-07|01:51:47.520] Cannot register RPC callback [invalidRets2] - error must the last return value 
[WARN] [04-07|01:51:47.520] Cannot register RPC callback [invalidRets3] - maximum 2 return values are allowed, got 3 
[WARN] [04-07|01:51:47.523] Cannot register RPC callback [invalidRets1] - error must the last return value 
[WARN] [04-07|01:51:47.523] Cannot register RPC callback [invalidRets2] - error must the last return value 
[WARN] [04-07|01:51:47.524] Cannot register RPC callback [invalidRets3] - maximum 2 return values are allowed, got 3 
[WARN] [04-07|01:51:47.527] Cannot register RPC callback [invalidRets1] - error must the last return value 
[WARN] [04-07|01:51:47.527] Cannot register RPC callback [invalidRets2] - error must the last return value 
[WARN] [04-07|01:51:47.527] Cannot register RPC callback [invalidRets3] - maximum 2 return values are allowed, got 3 
[WARN] [04-07|01:51:47.563] Cannot register RPC callback [invalidRets1] - error must the last return value 
[WARN] [04-07|01:51:47.563] Cannot register RPC callback [invalidRets2] - error must the last return value 
[WARN] [04-07|01:51:47.563] Cannot register RPC callback [invalidRets3] - maximum 2 return values are allowed, got 3 
[WARN] [04-07|01:51:56.015] Cannot register RPC callback [invalidRets1] - error must the last return value 
[WARN] [04-07|01:51:56.015] Cannot register RPC callback [invalidRets2] - error must the last return value 
[WARN] [04-07|01:51:56.015] Cannot register RPC callback [invalidRets3] - maximum 2 return values are allowed, got 3 
[WARN] [04-07|01:51:56.019] Cannot register RPC callback [invalidRets1] - error must the last return value 
[WARN] [04-07|01:51:56.019] Cannot register RPC callback [invalidRets2] - error must the last return value 
[WARN] [04-07|01:51:56.019] Cannot register RPC callback [invalidRets3] - maximum 2 return values are allowed, got 3 
[WARN] [04-07|01:51:56.103] Cannot register RPC callback [invalidRets1] - error must the last return value 
[WARN] [04-07|01:51:56.103] Cannot register RPC callback [invalidRets2] - error must the last return value 
[WARN] [04-07|01:51:56.103] Cannot register RPC callback [invalidRets3] - maximum 2 return values are allowed, got 3 
[WARN] [04-07|01:51:58.107] Cannot register RPC callback [invalidRets1] - error must the last return value 
[WARN] [04-07|01:51:58.107] Cannot register RPC callback [invalidRets2] - error must the last return value 
[WARN] [04-07|01:51:58.107] Cannot register RPC callback [invalidRets3] - maximum 2 return values are allowed, got 3 
[WARN] [04-07|01:52:32.735] Cannot register RPC callback [invalidRets1] - error must the last return value 
[WARN] [04-07|01:52:32.735] Cannot register RPC callback [invalidRets2] - error must the last return value 
[WARN] [04-07|01:52:32.735] Cannot register RPC callback [invalidRets3] - maximum 2 return values are allowed, got 3 
[WARN] [04-07|01:52:32.737] Cannot register RPC callback [invalidRets1] - error must the last return value 
[WARN] [04-07|01:52:32.737] Cannot register RPC callback [invalidRets2] - error must the last return value 
[WARN] [04-07|01:52:32.737] Cannot register RPC callback [invalidRets3] - maximum 2 return values are allowed, got 3 
[WARN] [04-07|01:52:32.737] Cannot register RPC callback [invalidRets1] - error must the last return value 
[WARN] [04-07|01:52:32.737] Cannot register RPC callback [invalidRets2] - error must the last return value 
[WARN] [04-07|01:52:32.737] Cannot register RPC callback [invalidRets3] - maximum 2 return values are allowed, got 3 
[WARN] [04-07|01:52:32.738] Cannot register RPC callback [invalidRets1] - error must the last return value 
[WARN] [04-07|01:52:32.738] Cannot register RPC callback [invalidRets2] - error must the last return value 
[WARN] [04-07|01:52:32.738] Cannot register RPC callback [invalidRets3] - maximum 2 return values are allowed, got 3 
[WARN] [04-07|01:52:32.740] [rpc] served                             method=unknown_method reqid=2 err="the method unknown_method does not exist/is not available"
[WARN] [04-07|01:52:32.741] Cannot register RPC callback [invalidRets1] - error must the last return value 
[WARN] [04-07|01:52:32.741] Cannot register RPC callback [invalidRets2] - error must the last return value 
[WARN] [04-07|01:52:32.741] Cannot register RPC callback [invalidRets3] - maximum 2 return values are allowed, got 3 
[WARN] [04-07|01:52:32.743] Cannot register RPC callback [invalidRets1] - error must the last return value 
[WARN] [04-07|01:52:32.743] Cannot register RPC callback [invalidRets2] - error must the last return value 
[WARN] [04-07|01:52:32.743] Cannot register RPC callback [invalidRets3] - maximum 2 return values are allowed, got 3 
[WARN] [04-07|01:52:32.744] Cannot register RPC callback [invalidRets1] - error must the last return value 
[WARN] [04-07|01:52:32.744] Cannot register RPC callback [invalidRets2] - error must the last return value 
[WARN] [04-07|01:52:32.744] Cannot register RPC callback [invalidRets3] - maximum 2 return values are allowed, got 3 
[WARN] [04-07|01:52:32.745] Cannot register RPC callback [invalidRets1] - error must the last return value 
[WARN] [04-07|01:52:32.745] Cannot register RPC callback [invalidRets2] - error must the last return value 
[WARN] [04-07|01:52:32.745] Cannot register RPC callback [invalidRets3] - maximum 2 return values are allowed, got 3 
[WARN] [04-07|01:52:32.746] [rpc] served                             method=test_echo reqid=2 err="missing value for required argument 0"
[WARN] [04-07|01:52:32.746] Cannot register RPC callback [invalidRets1] - error must the last return value 
[WARN] [04-07|01:52:32.747] Cannot register RPC callback [invalidRets2] - error must the last return value 
[WARN] [04-07|01:52:32.747] Cannot register RPC callback [invalidRets3] - maximum 2 return values are allowed, got 3 
[WARN] [04-07|01:52:32.748] [rpc] served                             method=test_echo reqid=2 err="missing value for required argument 0"
[WARN] [04-07|01:52:32.748] [rpc] served                             method=test_echo reqid=2 err="missing value for required argument 1"
[WARN] [04-07|01:52:32.750] Cannot register RPC callback [invalidRets1] - error must the last return value 
[WARN] [04-07|01:52:32.750] Cannot register RPC callback [invalidRets2] - error must the last return value 
[WARN] [04-07|01:52:32.750] Cannot register RPC callback [invalidRets3] - maximum 2 return values are allowed, got 3 
[WARN] [04-07|01:52:32.751] [rpc] served                             method=test_echo reqid=3 err="non-array args"
[WARN] [04-07|01:52:32.751] Cannot register RPC callback [invalidRets1] - error must the last return value 
[WARN] [04-07|01:52:32.751] Cannot register RPC callback [invalidRets2] - error must the last return value 
[WARN] [04-07|01:52:32.751] Cannot register RPC callback [invalidRets3] - maximum 2 return values are allowed, got 3 
[WARN] [04-07|01:52:32.752] Cannot register RPC callback [invalidRets1] - error must the last return value 
[WARN] [04-07|01:52:32.752] Cannot register RPC callback [invalidRets2] - error must the last return value 
[WARN] [04-07|01:52:32.752] Cannot register RPC callback [invalidRets3] - maximum 2 return values are allowed, got 3 
[WARN] [04-07|01:52:32.753] [rpc] served                             method=invalid_method reqid=2 err="the method invalid_method does not exist/is not available"
[WARN] [04-07|01:52:32.754] Cannot register RPC callback [invalidRets1] - error must the last return value 
[WARN] [04-07|01:52:32.754] Cannot register RPC callback [invalidRets2] - error must the last return value 
[WARN] [04-07|01:52:32.754] Cannot register RPC callback [invalidRets3] - maximum 2 return values are allowed, got 3 
[WARN] [04-07|01:52:32.754] Cannot register RPC callback [invalidRets1] - error must the last return value 
[WARN] [04-07|01:52:32.754] Cannot register RPC callback [invalidRets2] - error must the last return value 
[WARN] [04-07|01:52:32.755] Cannot register RPC callback [invalidRets3] - maximum 2 return values are allowed, got 3 
[WARN] [04-07|01:52:32.755] Cannot register RPC callback [invalidRets1] - error must the last return value 
[WARN] [04-07|01:52:32.755] Cannot register RPC callback [invalidRets2] - error must the last return value 
[WARN] [04-07|01:52:32.755] Cannot register RPC callback [invalidRets3] - maximum 2 return values are allowed, got 3 
[WARN] [04-07|01:52:32.757] Cannot register RPC callback [invalidRets1] - error must the last return value 
[WARN] [04-07|01:52:32.757] Cannot register RPC callback [invalidRets2] - error must the last return value 
[WARN] [04-07|01:52:32.757] Cannot register RPC callback [invalidRets3] - maximum 2 return values are allowed, got 3 
[WARN] [04-07|01:52:32.758] Cannot register RPC callback [invalidRets1] - error must the last return value 
[WARN] [04-07|01:52:32.758] Cannot register RPC callback [invalidRets2] - error must the last return value 
[WARN] [04-07|01:52:32.758] Cannot register RPC callback [invalidRets3] - maximum 2 return values are allowed, got 3 
[WARN] [04-07|01:52:32.760] Cannot register RPC callback [invalidRets1] - error must the last return value 
[WARN] [04-07|01:52:32.760] Cannot register RPC callback [invalidRets2] - error must the last return value 
[WARN] [04-07|01:52:32.760] Cannot register RPC callback [invalidRets3] - maximum 2 return values are allowed, got 3 
[WARN] [04-07|01:52:32.771] Cannot register RPC callback [invalidRets1] - error must the last return value 
[WARN] [04-07|01:52:32.771] Cannot register RPC callback [invalidRets2] - error must the last return value 
[WARN] [04-07|01:52:32.771] Cannot register RPC callback [invalidRets3] - maximum 2 return values are allowed, got 3 
[WARN] [04-07|01:52:44.363] Cannot register RPC callback [invalidRets1] - error must the last return value 
[WARN] [04-07|01:52:44.363] Cannot register RPC callback [invalidRets2] - error must the last return value 
[WARN] [04-07|01:52:44.363] Cannot register RPC callback [invalidRets1] - error must the last return value 
[WARN] [04-07|01:52:44.363] Cannot register RPC callback [invalidRets3] - maximum 2 return values are allowed, got 3 
[WARN] [04-07|01:52:44.363] Cannot register RPC callback [invalidRets2] - error must the last return value 
[WARN] [04-07|01:52:44.363] Cannot register RPC callback [invalidRets3] - maximum 2 return values are allowed, got 3 
[WARN] [04-07|01:52:44.363] Cannot register RPC callback [invalidRets1] - error must the last return value 
[WARN] [04-07|01:52:44.363] Cannot register RPC callback [invalidRets2] - error must the last return value 
[WARN] [04-07|01:52:44.363] Cannot register RPC callback [invalidRets3] - maximum 2 return values are allowed, got 3 
--- FAIL: TestClientCancelWebsocket (1.00s)
panic: read tcp 127.0.0.1:59236->127.0.0.1:33899: read: connection reset by peer [recovered, repanicked]

goroutine 66 [running]:
testing.tRunner.func1.2({0x117cd40, 0xc000059720})
	/opt/hostedtoolcache/go/1.25.8/x64/src/testing/testing.go:1872 +0x419
testing.tRunner.func1()
	/opt/hostedtoolcache/go/1.25.8/x64/src/testing/testing.go:1875 +0x683
panic({0x117cd40?, 0xc000059720?})
	/opt/hostedtoolcache/go/1.25.8/x64/src/runtime/panic.go:783 +0x132
github.com/erigontech/erigon/rpc.httpTestClient(0xc000324180, {0x11fcef1, 0x2}, 0xc000059120)
	/home/runner/work/erigon/erigon/rpc/client_test.go:619 +0x6b9
github.com/erigontech/erigon/rpc.testClientCancel({0x11fcef1, 0x2}, 0xc000102e00, {0x136dd10, 0xc000300c60})
	/home/runner/work/erigon/erigon/rpc/client_test.go:206 +0x256
github.com/erigontech/erigon/rpc.TestClientCancelWebsocket(0xc000102e00)
	/home/runner/work/erigon/erigon/rpc/client_test.go:166 +0x58
testing.tRunner(0xc000102e00, 0x1241000)
	/opt/hostedtoolcache/go/1.25.8/x64/src/testing/testing.go:1934 +0x21d
created by testing.(*T).Run in goroutine 1
	/opt/hostedtoolcache/go/1.25.8/x64/src/testing/testing.go:1997 +0x9d3

goroutine 1 [chan receive]:
testing.tRunner.func1()
	/opt/hostedtoolcache/go/1.25.8/x64/src/testing/testing.go:1891 +0x9ad
testing.tRunner(0xc00037e1c0, 0xc000053ae0)
	/opt/hostedtoolcache/go/1.25.8/x64/src/testing/testing.go:1940 +0x256
testing.runTests(0xc00035c3c0, {0x198f6a0, 0x28, 0x28}, {0x0?, 0x4bba45?, 0x1999960?})
	/opt/hostedtoolcache/go/1.25.8/x64/src/testing/testing.go:2475 +0x96d
testing.(*M).Run(0xc00037a140)
	/opt/hostedtoolcache/go/1.25.8/x64/src/testing/testing.go:2337 +0xed5
main.main()
	_testmain.go:129 +0x165

goroutine 37 [chan receive]:
```