`TestSetupGenesis` less concurrency (#17873)
because caused on Win:
```
    --- FAIL: TestSetupGenesis/custom_block_in_DB,_genesis_==_sepolia (0.54s)
panic: fail to open mdbx: mdbx_env_open: The paging file is too small for this operation to complete., label: temporary, trace: [kv_mdbx.go:310 kv_mdbx.go:424 genesis_write.go:312 genesis_write.go:222 genesis_write.go:259 genesis_write.go:245 genesis_test.go:247 genesis_test.go:305 testing.go:1792 asm_amd64.s:1700] [recovered]
```