make: fix make mocks (#14697)
1. fixes an issue raised by Som that `make mocks` is broken with the
below err:
```
PATH="/home/somnath/Documents/code/erigon/build/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/somnath/.vscode-server/cli/servers/Stable-4949701c880d4bdb949e3c0e6b400288da7f474b/server/bin/remote-cli:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/home/somnath/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/somnath/.vscode-server/data/User/globalStorage/github.copilot-chat/debugCommand" go generate -run "mockgen" ./...
2025/04/22 17:09:57 Loading input failed: load package: /home/somnath/Documents/code/erigon/txnprovider/shutter/internal/testhelpers/eon_tracker_mock_creator.go:27:42: undefined: MockEonTracker
/home/somnath/Documents/code/erigon/txnprovider/shutter/internal/testhelpers/slot_calculator_mock_creator.go:25:46: undefined: MockSlotCalculator
/home/somnath/Documents/code/erigon/txnprovider/shutter/internal/testhelpers/eon_tracker_mock_creator.go:29:82: undefined: MockEonTracker
/home/somnath/Documents/code/erigon/txnprovider/shutter/internal/testhelpers/slot_calculator_mock_creator.go:27:90: undefined: MockSlotCalculator
/home/somnath/Documents/code/erigon/txnprovider/shutter/internal/testhelpers/eon_tracker_mock_creator.go:30:29: undefined: MockEonTracker
/home/somnath/Documents/code/erigon/txnprovider/shutter/internal/testhelpers/eon_tracker_mock_creator.go:32:9: undefined: NewMockEonTracker
/home/somnath/Documents/code/erigon/txnprovider/shutter/internal/testhelpers/eon_tracker_mock_creator.go:47:18: undefined: MockEonTracker
/home/somnath/Documents/code/erigon/txnprovider/shutter/internal/testhelpers/eon_tracker_mock_creator.go:65:18: undefined: MockEonTracker
/home/somnath/Documents/code/erigon/txnprovider/shutter/internal/testhelpers/slot_calculator_mock_creator.go:28:29: undefined: MockSlotCalculator
/home/somnath/Documents/code/erigon/txnprovider/shutter/internal/testhelpers/slot_calculator_mock_creator.go:30:9: undefined: NewMockSlotCalculator
/home/somnath/Documents/code/erigon/txnprovider/shutter/internal/testhelpers/slot_calculator_mock_creator.go:39:18: undefined: MockSlotCalculator
```
2. fixes missing declarations of the `//go:generate mockgen` directive
for `consensus/chain_reader_mock.go` and `bor/bridge_reader_mock.go`
introduced in https://github.com/erigontech/erigon/pull/14484
3. fixes a missing declaration of the `//go:generate mockgen` directive
for `core/tracking/mocks` introduced in
https://github.com/erigontech/erigon/pull/10915 - since mockgen works
based on interfaces it doesn't really make sense to use mockgen for it
(tracing hooks are now struct based) - hence removing this mock
altogether and using a mock tracer struct approach in the 1 and only
test using this - `intra_block_state_logger_test.go`