use t.TempDir() in tests (#10774)
for
https://github.com/ledgerwatch/erigon/actions/runs/9517264736/job/26259577369?pr=10753#step:11:542
```
--- FAIL: TestBlockhash (0.01s)
    runtime_test.go:397: expected no error, got open /tmp/execute-vm/snapshots/salt-state.txt: no such file or directory
FAIL
```
don't use `/tmp` / `os.TempDir()` - because tests are run in-parallel.