execution/tests: add retry to engine api tests for no connection on win (#17195)
after https://github.com/erigontech/erigon/pull/17164 we got a flake in
this
[run](https://github.com/erigontech/erigon/actions/runs/17908063097/job/50913085203)
with:
```
engine_api_tester.go:223: 
Error Trace:	github.com/erigontech/erigon/execution/tests/engine_api_tester.go:223
			     github.com/erigontech/erigon/execution/tests/engine_api_tester.go:63
		             github.com/erigontech/erigon/execution/tests/engine_api_reorg_test.go:34
Error:      	Received unexpected error:
            	Post "http://127.0.0.1:58525/": dial tcp 127.0.0.1:58525: connectex: No connection could be made because the target machine actively refused it.
Test:       	TestEngineApiInvalidPayloadThenValidCanonicalFcuWithPayloadShouldSucceed
```

adding the corresponding err to the retry-able errors for the engine api
tester (it is an initialisation timing err)