[alpha] Move devel to alpha (#4112)
* penalize naughty peers on PoS (#4060)

* penalize naughty peers

* lint

* Small performance optimization (hash already calculated) (#4053)

* speedup logIndex test  (#4068)

* Torrent: increase network request size  (#4067)

* save

* save

* CI: run integration tests on trunk after PR is merged (#4075)

Running on PR close event tests the PR commit, not the final merged commit.
The final commit is tested by "push" event, but it appears as "skipped" in the list of devel ccmmits,
because "push" event was skipped by "if".

* Update header_algos.go (#4078)

* p2p: TestUDPv4_LookupIterator failures workaround (#4079)

--- FAIL: TestUDPv4_LookupIterator (1.36s)
155
    v4_lookup_test.go:168: handlePacket error: "unsolicited reply"
156

* CI: run integration tests on Windows (#4076)

* [erigon2] Support for binary tree commitments (#4077)

* binary tree

* Binary commitment tree

* [erigon2] Bin tree support

* Point to latest erigon-lib

Co-authored-by: Alexey Sharp <alexeysharp@Alexeys-iMac.local>

* CI: more caching (#4083)

Cache "go-build" containing cached build artifacts from the Go build system.
This saves up to:
  - 6 min on Linux (from 10 min to 4 min)
  - 3 min on macOS  (from 13 min to 10 min)
  - 7 min on Windows (from 27 min to 20 min)

Cache Windows deps (mingw, cmake).
This saves 6,5 min on Windows builds (from 20 min to 13,5 min)

* rpcdaemon: optimize tests (#4082)

* reuse the generated test blockchain across tests
* copy ChainPack to ensure test isolation

This improves the speed from 10s to 4s.

The package tests timeout can be reduced to 5s:

    go test ./cmd/rpcdaemon/commands -count 1 --timeout 5s

* Downloader atomic snapshot dir, step 1 (#4085)

* save

* save

* save

* [Docs] Add PoS downloader diagram (#4084)

* Extra comment for HeadersPOS

* Add PoS downloader diagram

* Revert "state_processor: fix ignored SkipAnalysis() result (#4046)" (#4087)

This reverts commit cf448036212b4a752f13e77a9c58732cfc2eebd5.

* Revert changes in decompressor (#4089)

Co-authored-by: Alexey Sharp <alexeysharp@Alexeys-iMac.local>

* Remove preverified hashes (#4088)

Co-authored-by: Alexey Sharp <alexeysharp@Alexeys-iMac.local>

* p2p: define DiscReason as uint8 (#4090)

Co-authored-by: Alexey Sharp <alexeysharp@Alexeys-iMac.local>

* remove metrics package, step 1 (#4094)

* atomic snapshot dir, step 2 (#4093)

* atomic snapshot dir

* atomic snapshot dir

* switch toml lib to release version (#4095)

* save

* save

* save (#4096)

* Snapshots: restore logInterval #4098

* torrent not found fix (#4101)

* Torrent: increase network-request size to 2Mb (#4100)

* Amend description of override.mergeForkBlock flag (#4106)

* p2p: move v4_lookup_test to integration tests (#4107)

The test is flaky when the reply timeout is too low.
Increasing the timeout makes it slow.

Move the test to the integration suite.
Having a higher timeout is fine there.

* make: wmake refactoring (#4105)

* list "all" targets explicitly
* add missing targets
* add missing build flags
* add test-integration target
* show tests output
* use wmake test on CI
* update submodules for all targets (like Makefile)
* remove unused function Test-Administrator

* Snapshots: atomic dir, step 3 (#4103)

* up linter version (#4108)

* save

* save

* save

* Rename sentry.ControlServerImpl to sentry.MultyClient and sentry.SentryServerImpl to sentry.GrpcServer #444

* Simplify header downloader (#4104)

* Simplify header downloader

* Remove VerifyQueue

* Fix

* More fixes

* Fix

* Break out of the loop

Co-authored-by: Alexey Sharp <alexeysharp@Alexeys-iMac.local>

* RPCDaemon: open snapshots on startup (because now snapshots dir is atomic), even if no Erigon available (#4110)

* save

* save

* save

* save

* save

* save

* Bumb alpha version

* Update to erigon-lib alpha

Co-authored-by: Giulio rebuffo <giulio.rebuffo@gmail.com>
Co-authored-by: Andrew Ashikhmin <34320705+yperbasis@users.noreply.github.com>
Co-authored-by: Alex Sharov <AskAlexSharov@gmail.com>
Co-authored-by: battlmonstr <battlmonstr@users.noreply.github.com>
Co-authored-by: Alexey Sharp <alexeysharp@Alexeys-iMac.local>
Co-authored-by: Alex Sharp <alexsharp@Alexs-MacBook-Pro.local>