execution/eth1: fix flake in TestValidateChainWithLastTxNumOfBlockAtStepBoundary (#18879)
fixes a flaky test I introduced in
https://github.com/erigontech/erigon/pull/18858

CI run:
https://github.com/erigontech/erigon/actions/runs/21483225590/job/61885074571
```
--- FAIL: TestValidateChainWithLastTxNumOfBlockAtStepBoundary (0.04s)
    ethereum_execution_test.go:57:
        	Error Trace:	/Users/runner/work/erigon/erigon/execution/eth1/ethereum_execution_test.go:57
        	Error:      	Not equal:
        	            	expected: 0
        	            	actual  : 5
        	Test:       	TestValidateChainWithLastTxNumOfBlockAtStepBoundary
```